export const accessStructure = [
  {
    id: 1,
    name: "John Heart",
    title: "SH",
    category: "Root",
    workplace: "SH",
    doortype: "BS",
    items: [
      {
        id: 2,
        name: "Samantha Bright",
        title: "Reader1",
        category: "Reader",
        workplace: "SH",
        doortype: "BS",
      },
      {
        id: 3,
        name: "Arthur Miller",
        title: "Reader2",
        category: "Reader",
        workplace: "SH",
        doortype: "BS",
      },
      {
        id: 4,
        name: "Robert Reagan",
        title: "Reader3",
        category: "Reader",
        workplace: "SH",
        doortype: "BS",
      },
      {
        id: 5,
        name: "Greta Sims",
        title: "Reader4",
        category: "Reader",
        workplace: "SH",
        doortype: "BS",
      },
    ],
  },
  {
    id: 6,
    title: "KK",
    category: "Root",
    workplace: "KK",
    doortype: "BS",
    items: [
      {
        id: 7,
        name: "Samantha Bright",
        title: "Reader1",
        category: "Reader",
        workplace: "KK",
        doortype: "BS",
      },
      {
        id: 8,
        name: "Arthur Miller",
        title: "Reader2",
        category: "Reader",
        workplace: "KK",
        doortype: "BS",
      },
      {
        id: 9,
        name: "Robert Reagan",
        title: "Reader3",
        category: "Reader",
        workplace: "KK",
        doortype: "BS",
      },
    ],
  },
];
