export const dragAccessStructure = [
  {
    id: 1,
    head_id: -1,
    title: "SH",
    category: "Root",
    workplace: "SH",
    doortype: "BS",
  },
  {
    id: 2,
    head_id: 1,
    title: "Reader1",
    category: "Reader",
    workplace: "SH",
    doortype: "BS",
  },
  {
    id: 3,
    head_id: 1,
    title: "Reader2",
    category: "Reader",
    workplace: "SH",
    doortype: "BS",
  },
  {
    id: 4,
    head_id: 1,
    title: "Reader3",
    category: "Reader",
    workplace: "SH",
    doortype: "BS",
  },
  {
    id: 5,
    head_id: 1,
    title: "Reader4",
    category: "Reader",
    workplace: "SH",
    doortype: "BS",
  },
  {
    id: 6,
    head_id: -1,
    title: "KK",
    category: "Root",
    workplace: "KK",
    doortype: "BS",
  },
];
