export const accessCount = [
  {
    id: 1,
    region: "SH",
    country: "신화",
    city: "가져요",
    amount: 1000,
    date: new Date("2023-01-21"),
  },
  {
    id: 2,
    region: "SH",
    country: "신화",
    city: "유딩딩",
    amount: 2000,
    date: new Date("2023-01-21"),
  },
  {
    id: 3,
    region: "SH",
    country: "신화",
    city: "박가다",
    amount: 5000,
    date: new Date("2023-01-21"),
  },
  {
    id: 4,
    region: "KK",
    country: "이미영",
    city: "이미영",
    amount: 2000,
    date: new Date("2024-01-21"),
  },
  {
    id: 5,
    region: "KK",
    country: "김바다",
    city: "김바다",
    amount: 5000,
    date: new Date("2024-09-21"),
  },
];
